# csem2to4box config
InputFiles:
    salt: sampleLEsalt1.nc
    temp: sampleLEtemp1.nc
    velN: sampleLEvvel1.nc
    MOC: sampleLEmoc1.nc
    grid: sampleLEsalt1.nc
    datapath: ./data/
    gswLibraryPath: /path/toyour/gsw/
    source: LE
    lowmemory: 1
coordinates:
    latSouth: -45 
    latNorth1: 45 
    latNorth2: 65
    depthH: 200
parameters:
    diffusionGM: 3000
    diffusionRedi: 600
    diffusionVert: 0.16e-4
    epsilon: 1.4e-4
OutputFiles:
    matlab: zonalmeanTestLE.mat
    atlantic: zonalmeanAtestLE.nc 
    pacific: zonalmeanPtestLE.nc
    box: boxTestLE.nc
